# Generated by Django 5.1 on 2024-08-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('En stock', 'En stock'), ('Sin stock', 'Sin stock')], default='En stock', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('date_of_admision', models.DateTimeField(verbose_name='fecha de ingreso')),
                ('price', models.IntegerField()),
                ('publication_date', models.DateField(verbose_name='fecha de publicacion')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='imagen de portada')),
                ('synopsis', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('in_stock', models.PositiveIntegerField(default=1, help_text='Number of available copies of the book.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='books.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
            ],
        ),
    ]
