# Generated by Django 4.2 on 2025-12-08 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_of_admision',
        ),
        migrations.RemoveField(
            model_name='book',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock_quantity',
            field=models.IntegerField(default=1, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
