# Generated by Django 4.2 on 2025-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_date_of_admision_remove_book_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
