# Generated by Django 4.2 on 2025-12-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='book_covers/CoverNotAvailable.jpg', null=True, upload_to='book_covers/', verbose_name='imagen de portada'),
        ),
    ]
